# Copyright (c) 2019, Pete Batard <pete@akeo.ie>
# SPDX-License-Identifier: BSD-3-Clause

image: Ubuntu1804

skip_non_tags: true

install:
  sh: |-
      sudo apt-get update -qq
      sudo -E apt-get install -y acpica-tools gcc-aarch64-linux-gnu python3-distutils uuid-dev wget
      git submodule update --init --recursive

build_script:
  sh: ./build_firmware.sh

after_build:
  sh: |-
      7z a RPi4_UEFI_Firmware_$APPVEYOR_REPO_TAG_NAME.zip $APPVEYOR_BUILD_FOLDER/Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd $APPVEYOR_BUILD_FOLDER/bcm2711-rpi-4-b.dtb $APPVEYOR_BUILD_FOLDER/config.txt $APPVEYOR_BUILD_FOLDER/fixup4.dat $APPVEYOR_BUILD_FOLDER/start4.elf overlays/miniuart-bt.dtbo $APPVEYOR_BUILD_FOLDER/Readme.md
      sha256sum $APPVEYOR_BUILD_FOLDER/Firmware/*.fd $APPVEYOR_BUILD_FOLDER/Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd RPi4_UEFI_Firmware_$APPVEYOR_REPO_TAG_NAME.zip

artifacts:
  - path: 'Firmware/RPI_M4D.fd'
    name: mUART, 4GB (ACPI+DT), DEBUG
  - path: 'Firmware/RPI_M3D.fd'
    name: mUART, 3GB (ACPI), DEBUG
  - path: 'Firmware/RPI_P4D.fd'
    name: PL011, 4GB (ACPI+DT), DEBUG
  - path: 'Firmware/RPI_P3D.fd'
    name: PL011, 3GB (ACPI), DEBUG
  - path: 'Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd'
    name: PL011, 3GB (ACPI), RELEASE
  - path: '*.zip'
    name: RPi 4 UEFI Firmware

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: Raspberry Pi 4 UEFI Firmware $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: w5YuQOim+G+U7FxxrL0BH6t0trCWKCs9DMZlF4xqF2XGC6SymzwaJrPWrKeeJHPK
  artifact: /.*\.zip/
  draft: false
  prerelease: false
